crds:
  enabled: true

alertmanager:
  ingress:
    enabled: false

grafana:
  enabled: true
  ingress:
    enabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.observability.svc.cluster.local:3100
      access: proxy
      isDefault: false

prometheus:
  ingress:
    enabled: false
  thanosService:
    enabled: false
  thanosServiceExternal:
    enabled: false
  thanosServiceMonitor:
    enabled: false
  thanosIngress:
    enabled: false
  prometheusSpec:
    thanos: null

thanosRuler:
  enabled: false
