injector:
  enabled: false

ui:
  enabled: true

server:
  dev:
    enabled: false
  ha:
    enabled: false
  standalone:
    enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: longhorn-single
