apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.92.5
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/apps/networking/tailscale/values.yaml
    - repoURL: https://github.com/algebananazzzzz/homelab-manifests
      targetRevision: main
      ref: values
    - repoURL: https://github.com/algebananazzzzz/homelab-manifests
      targetRevision: main
      path: apps/networking/tailscale/manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
