apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tailscale-credentials
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: "tailscale-credentials"
        property: "clientId"
    - secretKey: client_secret
      remoteRef:
        key: "tailscale-credentials"
        property: "clientSecret"
