apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.0
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/apps/storage/longhorn/values.yaml
    - repoURL: git@github.com:algebananazzzzz/homelab-manifests.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
