apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: default
  destination:
    namespace: openfaas
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://openfaas.github.io/faas-netes/
      chart: openfaas
      targetRevision: 14.2.135
      helm:
        releaseName: openfaas
        valueFiles:
          - $values/apps/serverless/openfaas/values.yaml
    - repoURL: git@github.com:algebananazzzzz/homelab-manifests.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:algebananazzzzz/homelab-manifests.git
      targetRevision: main
      path: apps/serverless/openfaas/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
