apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/vault/application.yaml
  # - secrets/external-secrets/application.yaml
  - networking/cilium/application.yaml
  - storage/longhorn/application.yaml
  # - secrets/secrets/application.yaml
  # - networking/tailscale/application.yaml
  # - observability/prometheus/application.yaml
  # - observability/loki/application.yaml
  # - observability/fluent-bit/application.yaml
