apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.0
      helm:
        releaseName: cilium
        valueFiles:
          - $values/apps/networking/cilium/values.yaml
    - repoURL: git@github.com:algebananazzzzz/homelab-manifests.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:algebananazzzzz/homelab-manifests.git
      targetRevision: main
      path: apps/networking/cilium/manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true