apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.55.0
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $values/apps/observability/fluent-bit/values.yaml
    - repoURL: https://github.com/algebananazzzzz/homelab-manifests
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
